version: "3"
services:
  psql:
    image: postgres:14
    container_name: psql
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: chats
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4321
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  psql:
    driver: local